---
- name: Grab F5 Facts
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - bigip_vars.yml

  tasks: 
    
    - name: Collect F5 Big-IP Facts
      f5networks.f5_modules.bigip_device_info:
        gather_subset:
          - system-info
        provider: 
          server: "{{ f5_server }}"
          user: "{{ f5_user }}"
          password: "{{ f5_password }}"
          server_port: 8443
          validate_certs: false
      register: device_facts

    - name: Display F5 Big-IP System Info
      debug: 
        var: device_facts

    - name: DISPLAY ONLY THE MAC ADDRESS
      debug:
        var: device_facts['system_info']['base_mac_address']

    - name: DISPLAY ONLY THE VERSION
      debug:
        var: device_facts['system_info']['product_version']
