---
- name: Add nodes to the F5 Big IP Appliance
  hosts: localhost
  gather_facts: false
  vars:
    f5_user: "{{ lookup('env', 'F5_USERNAME') }}"
    f5_password: "{{ lookup('env', 'F5_PASSWORD') }}"

  tasks:

    - name: Add nods to the F5
      f5networks.f5_modules.bigip_node:
        provider:
          server: "{{ f5_server }}"
          user: "{{ f5_user }}"
          password: "{{ f5_password }}"
          server_port: 8443
          no_f5_teem: true
          validate_certs: false
        host: "{{ item.host }}"
        name: "{{ item.name }}"
      loop: "{{ nodes }}"
