---
- name: Create a Load Balancing Pool on the F5 Applicance
  hosts: localhost
  gather_facts: false
  vars:
    f5_user: "{{ lookup('env', 'F5_USERNAME') }}"
    f5_password: "{{ lookup('env', 'F5_PASSWORD') }}"

  tasks:

    - name: Create a Load Balancing Pool
      f5networks.f5_modules.bigip_pool:
        provider:
          server: "{{ f5_server }}"
          user: "{{ f5_user }}"
          password: "{{ f5_password }}"
          server_port: 8443
          validate_certs: false
          no_f5_teem: true
        name: "{{ pool_name }}"
        lb_method: "round-robin"
        monitors: "/Common/http"
        monitor_type: "and_list"
