---
- name: Grab F5 Facts
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Collect F5 Big-IP Facts with f5_bigip Collection
      f5networks.f5_bigip.bigip_device_info:
        gather_subset:
          - all
