---
- name: Grab F5 Facts
  hosts: localhost
  gather_facts: false
  vars:
    f5_user: "{{ lookup('env', 'F5_USERNAME') }}"
    f5_password: "{{ lookup('env', 'F5_PASSWORD') }}"

  tasks:

    - name: Collect F5 Big-IP Facts
      f5networks.f5_modules.bigip_device_info:
        gather_subset:
          - system-info
        provider:
          server: "{{ f5_server }}"
          user: "{{ f5_user }}"
          password: "{{ f5_password }}"
          server_port: 8443
          validate_certs: false
          no_f5_teem: true
      register: device_facts

    - name: Display F5 Big-IP System Info
      ansible.builtin.debug:
        var: device_facts
