---
version: 2

ansible_config: ansible.cfg

dependencies:
  galaxy: requirements.yml

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest
  builder_image:
    name: registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:latest
